### PR TITLE
i18n/it: Italian translation

### PR DESCRIPTION
**Pull request by Salvaju29ro**
Hi, I tried to translate the software into Italian and the translation of the .yml files is actually complete, but the test build fails here:

```
 @ ../test/main.js 24:0-39:2

webpack 5.38.1 compiled with 1 error in 61896 ms
Warning:  Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

it is my first experience ever and I don't know what the error depends on
I cannot rule out that I have done everything wrong

### CODE REVIEW

**Comment by bastimeyer** [comment]
Thanks for submitting the PR and adding new Italian translations. Much appreciated!

https://github.com/streamlink/streamlink-twitch-gui/pull/823/checks?check_run_id=3401019859#step:8:11
The build fails because of invalid YAML syntax. Unfortunately the YAML loader doesn't pass its error message to the build chain and it gets swallowed by a different error when it tries to access the AST (abstract syntax tree) while analyzing the translation file.

Looks like you've accidentally deleted the `growl` property in the `settings.yml` file at line 523.
```diff
diff --git a/src/app/locales/it/settings.yml b/src/app/locales/it/settings.yml
index fa07f2ff..ea7e5c22 100644
--- a/src/app/locales/it/settings.yml
+++ b/src/app/locales/it/settings.yml
@@ -520,6 +520,7 @@ notifications:
                 name: Notifiche Toast di Windows
                 description: Native notifications on Windows 8+
                 notes: \"Banner notifiche\" deve essere abilitato nelle preferenze di sistema
+            growl:
                 name: Notifiche Growl
                 description: Third-party notification service for Windows, macOS and Linux
                 notes: Requires Growl to be installed and running on the system
```

There are however a couple of other mistakes which make the build fail:

```
>> Checking for missing translation keys in locales
>> fr: settings.player.players.mpv.attributes.no-keepaspect-window.checkbox
>> fr: settings.player.players.mpv.attributes.no-keepaspect-window.description
>> fr: settings.player.players.mpv.attributes.no-keepaspect-window.title
>> it: modal.streaming.body.error.hosting
>> it: modal.streaming.body.error.internal
>> it: modal.streaming.body.error.no-streams-found
>> it: modal.streaming.body.error.player
>> it: modal.streaming.body.error.provider
>> it: modal.streaming.body.error.timeout
>> it: modal.streaming.body.error.unable-to-open
>> it: modal.streaming.body.error.version
>> it: modal.streaming.header.error.hosting
>> it: modal.streaming.header.error.internal
>> it: modal.streaming.header.error.log
>> it: modal.streaming.header.error.no-streams-found
>> it: modal.streaming.header.error.player
>> it: modal.streaming.header.error.provider
>> it: modal.streaming.header.error.timeout
>> it: modal.streaming.header.error.unable-to-open
>> it: modal.streaming.header.error.version
>> pt-br: settings.player.players.mpv.attributes.no-keepaspect-window.checkbox
>> pt-br: settings.player.players.mpv.attributes.no-keepaspect-window.description
>> pt-br: settings.player.players.mpv.attributes.no-keepaspect-window.title
>> ru: settings.player.players.mpv.attributes.no-keepaspect-window.checkbox
>> ru: settings.player.players.mpv.attributes.no-keepaspect-window.description
>> ru: settings.player.players.mpv.attributes.no-keepaspect-window.title

>> Checking for invalid translation keys in application code
>> Success

>> Checking for unused translation keys in application code
>> Success

>> Checking for missing/invalid translation variables
>> Missing variable in it.routes.featured.summary: viewers
>> Invalid variable in it.routes.featured.summary: spettatori

>> Checking for missing/invalid translation parameters
>> Success
```

**Comment by bastimeyer** [comment]
This diff fixes the errors:
```diff
diff --git a/src/app/locales/it/modal.yml b/src/app/locales/it/modal.yml
index a1c54d60..c36c8c5c 100644
--- a/src/app/locales/it/modal.yml
+++ b/src/app/locales/it/modal.yml
@@ -49,7 +49,7 @@ streaming:
         launching: "Lanciando: "
         watching: "Guardando: "
         ended: "Stream concluso: "
-        Error:
+        error:
             log: "Errore: impossibile avviare lo stream"
             provider: "Errore: {provider} configurazione errata"
             player: "Errore: configurazione errata lettore"
@@ -62,7 +62,7 @@ streaming:
     body:
         launching: "In attesa che {provider} avii lo stream..."
         ended: "Vuoi riavviare lo streaming ora?"
-        Errore:
+        error:
             provider: "Si prega di controllare le impostazioni e/o (re)installare {provider}."
             player: "Si prega di controllare le impostazioni del lettore."
             version: "La versione v{version} non rispetta i requisiti minimi (v{required})."
diff --git a/src/app/locales/it/routes.yml b/src/app/locales/it/routes.yml
index 9796435b..22e8908a 100644
--- a/src/app/locales/it/routes.yml
+++ b/src/app/locales/it/routes.yml
@@ -29,7 +29,7 @@ about:
 featured:
     header: Featured Channels
     empty: Impossibile caricare l'elenco dei canali in primo piano!
-    summary: Ci sono {spettatori} persone che stanno guardando {channels} live streaming in questo momento!
+    summary: Ci sono {viewers} persone che stanno guardando {channels} live streaming in questo momento!
 games:
     header: Top Games
     empty: L'elenco restituito dei migliori giochi è vuoto.
diff --git a/src/app/locales/it/settings.yml b/src/app/locales/it/settings.yml
index fa07f2ff..ea7e5c22 100644
--- a/src/app/locales/it/settings.yml
+++ b/src/app/locales/it/settings.yml
@@ -520,6 +520,7 @@ notifications:
                 name: Notifiche Toast di Windows
                 description: Native notifications on Windows 8+
                 notes: \"Banner notifiche\" deve essere abilitato nelle preferenze di sistema
+            growl:
                 name: Notifiche Growl
                 description: Third-party notification service for Windows, macOS and Linux
                 notes: Requires Growl to be installed and running on the system
```

**Comment by Salvaju29ro** [comment]
@bastimeyer Thanks. During the writing I had not really realized it. I corrected.

**Comment by Salvaju29ro** [comment]
@bastimeyer Thanks. During the writing I had not really realized it. I should have corrected.

**Comment by bastimeyer** [comment]
All good now.

I had a quick look at the changes, and I obviously can't comment on the translations themselves as I don't speak Italian, but there are a couple of lines left which still need to get translated. Not sure if you're still working on this, or if you forgot or if something's unclear from missing context. If you have any questions, please ask, so I can help with providing the right context for the specific lines.

In regards to the commit log, once you've finished translating and once there aren't any mistakes left, please tell me, so I can rebase and clean it up, because I can't merge it like it is right now. Won't be a problem though, so don't worry.

Thanks again for submitting new translations!

**Comment by Salvaju29ro** [comment]
> Tutto bene ora.
> 
> Ho dato una rapida occhiata alle modifiche, e ovviamente non posso commentare le traduzioni stesse perché non parlo italiano, ma ci sono ancora un paio di righe che devono ancora essere tradotte. Non sono sicuro se ci stai ancora lavorando, o se te ne sei dimenticato o se qualcosa non è chiaro dal contesto mancante. Se hai domande, chiedi pure, così posso aiutarti a fornire il contesto giusto per le linee specifiche.
> 
> Per quanto riguarda il registro di commit, una volta che hai finito di tradurre e una volta che non ci sono più errori, per favore dimmelo, così posso rebase e ripulirlo, perché non posso unirlo come è adesso. Comunque non sarà un problema, quindi non preoccuparti.
> 
> Grazie ancora per aver inviato nuove traduzioni!

it is possible that some lines have forgotten it, even if I remember leaving something behind because they were almost untranslatable terms in another language (at least Italian)

Could you tell me which lines they are? Otherwise I'm looking for them

**Review by bastimeyer — COMMENTED** [review]
Ok, I had another look at the changes and found a few lines which were not translated. I'm not sure though if this was intentional or not.

I also had a look at the rendered application and couldn't find any layout related issues, which is good.

If you're happy with the translations and if you think that no mistakes are left, then I will go ahead and rebase / clean up the commit log for you, so this can be properly merged. Since you didn't branch off and submitted your pull request from your fork's master branch, this might cause problems, but we'll see.

**Comment by Salvaju29ro** [comment]
Hi, I took another look at the translations and there are actually some untranslated terms on purpose

Example:

terms like stream(s), streaming, Vodcast, chat, followers actually have a translation, but speaking of twitch it makes no sense to do so, because in this case the "original" terms are used, they are not translated

I may have missed some technical IT term, but in this case I think we should wait for a possible feedback from another Italian when he will use the software


> If you're happy with the translations and if you think that no mistakes are left, then I will go ahead and rebase / clean up the commit log for you, so this can be properly merged. Since you didn't branch off and submitted your pull request from your fork's master branch, this might cause problems, but we'll see.

is it possible to do it now?
I'm not sure how to do it, but if it's possible I'll try

**Comment by bastimeyer** [comment]
> terms like stream(s), streaming, Vodcast, chat, followers actually have a translation, but speaking of twitch it makes no sense to do so, because in this case the "original" terms are used, they are not translated

This is okay and expected. It's even worse in German.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Translating#41-accuracy--context

I mentioned these lines in particular because there were similar ones where you already added translations.

> I'm not sure how to do it, but if it's possible I'll try

Since you said that this is your first time submitting a pull request and since it looks like you've made the changes by using GitHub's website (which is rather awkward), I'm going to do this for you, because your PR branch obviously can't rebase without using git's command line interface or a git GUI frontend (that doesn't suck).

**Comment by bastimeyer** [comment]
I decided to merge this, since it looks good now.

Once again, thank you very much for your translations. If you spot any mistakes or if you think that something needs to be further improved, don't hesitate to open a new pull request.

As you can see, I rebased your changes (I had to squash them and remove commits with unrelated changes in `/build`) and force-pushed onto your master branch which you've used for submitting this pull request. This means that due to the merge commit, your fork's master branch and the master branch here have diverged now, which means you'll need to fix this at some point if you want to submit more pull requests.

This is the clean solution, but you can also delete your fork and re-clone:

```bash
# clone your fork
git clone git@github.com:Salvaju29ro/streamlink-twitch-gui.git
cd streamlink-twitch-gui
# add upstream remote
git remote add upstream https://github.com/streamlink-streamlink-twitch-gui.git
# fetch both remotes
git fetch --all
# temporarily checkout upstream's master branch
git checkout upstream/master
# force-update your local master branch to the commit of upstream's master branch
git branch --force master upstream/master
# checkout your local master branch again
git checkout master
# force-push the corrected master branch to your fork in order to fix the diverged branches
git push --force origin master
```

**Pull request merged**
