### PR TITLE
i18n/zh-tw translation update

### PR DESCRIPTION
**Pull request by dxball**
- [x] update channel setting translation added by 9b15302
- [x] update fade out translation
- [x] review hotkey translation

### CODE REVIEW

**Comment by bastimeyer** [comment]
Thanks, much appreciated as always.
There will be a few additional lines once I've added #723, so I'm not going to merge this yet.

Also, I've spotted the "help wanted" comment on the fade out streams option. Is there something unclear regarding the fade out feature, or is it about the translation (which I can obviously can not help with :sweat_smile:) ?

**Comment by bastimeyer** [comment]
Oh, and if there are more translations needed for certain hotkey codes, feel free to add them, as the list is not static.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Translating#28-hotkeys

**Comment by dxball** [comment]
> Thanks, much appreciated as always.
> There will be a few additional lines once I've added #723, so I'm not going to merge this yet.

I'll update the translation later 👍 

> 
> Also, I've spotted the "help wanted" comment on the fade out streams option. Is there something unclear regarding the fade out feature, or is it about the translation (which I can obviously can not help with 😅) ?

I'm not quite sure what **fade out** streams feature mean 😳. Does it mean something to be filtered out of the list?

> Oh, and if there are more translations needed for certain hotkey codes, feel free to add them, as the list is not static.
Ok, I'll take a look.

**Comment by bastimeyer** [comment]
> Does it mean something to be filtered out of the list?

No, it makes the streams not matching the language selection blend in with the background color, making them less visible, so that only matching streams are fully visible and therefore highlighted. All streams are shown in the list though. The filter out option on the other hand fully "removes" the non-matching streams (done via an API request parameter).

**Comment by bastimeyer** [comment]
Thanks!

**Pull request merged**
