### PR TITLE
Add translation for zh-tw

### PR DESCRIPTION
**Pull request by dxball**

### CODE REVIEW

**Comment by bastimeyer** [comment]
Thanks for submitting!
Can you rebase to master please? There was an issue related to MomentJS and its used locale in the test coverage run which I noticed earlier today while translating to German. I don't know why it's only failing in the coverage run and not in the regular test run, but I fixed the failing test, so that your PR should be working once rebased to master. Thanks again!

**Comment by dxball** [comment]
I've rebase to master, but the ci still failed 😭

**Comment by bastimeyer** [comment]
Yeah, the i18n system is still a bit rough around the edges. One test is failing only on Windows, which is once again a bit surprising. I'll have a look at it...

**Comment by dxball** [comment]
I've fix the 'Twtich' typo ☺️

**Comment by bastimeyer** [comment]
@dxball There are a couple of missing translations left. Could you please add them, so I can merge this? Thank you!

**Comment by dxball** [comment]
@bastimeyer sorry.. I thought there will be someone can help the translation :open_mouth:

**Comment by bastimeyer** [comment]
I'm having trouble finding a font that includes all of the used glyphs here. Streamlink Twitch GUI uses Roboto as primary font. Android does the same, but falls back to Noto Sans for CJK fonts.
I was trying to add Noto Sans from two of the available npm packages, but both of them seem to be limited to latin, cyrillic and greek letters. I don't want to let the app use the fonts installed on the user's system, because it's inconsistent. Same issue with other similar fonts, like Droid Sans. Why are there no npm packages for this? Am I missing something here?

- https://yarnpkg.com/en/package/notosans-fontface
- https://yarnpkg.com/en/package/typeface-noto-sans

**Comment by dxball** [comment]
I've no idea about the font issue :sweat_smile:

**Comment by bastimeyer** [comment]
Thanks again for the translations! :+1: 

I've decided to not include other fonts. The Noto Sans CJK font family is way too large to embed it into the app and it's not worth the effort. However, the app is now properly referring to the Noto Sans system fonts, if installed on the user's system. This should be good enough.
2e5bc8c6f7a65563f549fa25367ff3d30e1ed431

**Pull request merged**
